### ISSUE TITLE
Syntax Error on Version 1.3.0

### ISSUE THREAD

**Issue by Adkaiser** [aws/amazon-cognito-auth-js#184]
After installing v1.3.0 via npm, our app is encountering the following error during Jest unit tests:
```
node_modules/amazon-cognito-auth-js/lib/index.js:18
    export { default as CognitoAccessToken } from './CognitoAccessToken';
    ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/@aws-amplify/auth/src/Auth.ts:52:1)
      at Object.<anonymous> (node_modules/@aws-amplify/auth/src/index.ts:14:1)
```

**Comment by manueliglesias** [comment]
Hi @Adkaiser 

Can you verify if 1.3.1 is working for you?

**Comment by Adkaiser** [comment]
Confirmed, this is working for me now on 1.3.1. Thanks a bunch.
