### ISSUE TITLE
Symbol is undefined on IE 11

### ISSUE THREAD

**Issue by thbehlau** [aws/amazon-cognito-auth-js#192]
Using the library for ADFS SAML authentication and it is working fine except for IE 11.  
I'm getting the following error message:
>> ReferenceError: 'Symbol' is undefined

```
HTML1300: Navigation occurred.
vaultpro-tools.rentprogress.com
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
test.xxx.com
Let do the authentication
ReferenceError: 'Symbol' is undefined
at value (https://test.xxx.com/bower_components/amazon-cognito-auth-js/dist/amazon-cognito-auth.min.js:33:14818)
at value (https://test.xxx.com/bower_components/amazon-cognito-auth-js/dist/amazon-cognito-auth.min.js:33:10588)
at authenticate (https://test.xxx.com/bower_components/SharedWebApp/app/services/user.service.js:23:3)
at Anonymous function (https://test.xxx.com/app/VaultProTools.js:40:15)
at invoke (https://test.xxx.com/bower_components/angular/angular.js:4665:9)
at Anonymous function (https://test.xxx.com/bower_components/angular-route/angular-route.min.js:11:125)
at forEach (https://test.xxx.com/bower_components/angular/angular.js:336:11)
at Anonymous function (https://test.xxx.com/bower_components/angular-route/angular-route.min.js:11:99)
at processQueue (https://test.xxx.com ...
location path:/
undefined

```

**Comment by justin-dunham** [comment]
Same issue. Only appears in IE 11.
